### ISSUE TITLE
Placeholder after Reboot as Type in SmartThings

### ISSUE THREAD

**Issue by GaoMax** [veista/smartthings#10]
Hi! 
After your fix the integration loaded perfectly. But I realised, that I had no optional mode for WindFree HA. In SmartThings it shows 
supportedAcOptionalMode:
[
    "off",
    "windFree"
].
I rebooted the AC and it returned to it's original state in SmartThings Dev Portal "placeholder", the integration could not load. After I changed it in SmartThings back to Samsung OCF Air Conditioner, the devices became available in HA again, but unfortunately still without the Option to use WindFree.

**Comment by veista** [comment]
Hi. Are you running in cool mode? If you switch windfree on in heat mode it crashes the integration or errors out. This is the case atleast in my model. Also windfree is not available in st mobile app in heat or auto/heatcool. That is why i had to disable it.

**Comment by veista** [comment]
If your model supports windfree in heat mode, I can instruct you how to fix it temporarily. This is a tricky thing to fix permanently since there is this bug in many models that it give a non ST standard response if windfree is selected when in heat or auto mode.

**Comment by GaoMax** [comment]
I‘m trying with cool mode. I don’t see the option unfortunately. When I turn it on using the app, this is what I see in HA:
![Uploading 8D7FFE98-112C-4A11-B042-1EB6B39FEDAB.png…]()

**Comment by veista** [comment]
Ok. It seems that there are bigger issues with your setup. Can you please print me the full page of data according to issue 6.

**Comment by veista** [comment]
Did you add the integration when your ac was in cool mode?

**Comment by GaoMax** [comment]
I did just try to add the integration with AC in Cool mode and WindFree on. No Change unfortunately. Delete it before trying.
https://pastebin.com/Zk86K5EZ this is my entire data

**Comment by veista** [comment]
Ok. Thanks. I will try to debug this with your data when I have the chance.

**Comment by veista** [comment]
Btw. Can you select heat mode in HA? In your data heat is not in supported ac modes. It is in heat mode , so this just another bug in the samsung devices.

**Comment by veista** [comment]
Hi. For the life of me, I cannot replicate your problem. I found one bug in my code which could explain this problem. Can you please try the newest update.

**Comment by veista** [comment]
Can you also give me your real device model and explain how your setup works? I think we need to take some bigger tools out.

**Comment by GaoMax** [comment]
Hi Veista,
thank you for your help. Here is the curl content: https://pastebin.com/Vt3gH2CF.
My Setup is the following:
MIM-H04EN is my control unit
I have 2x AM 056  NN1DEH
and 3x AM 028  NN1DEH

**Comment by veista** [comment]
Hi. Thanks. The data seems to cut short. Could you please resend?

So is this data from your controller MIM-H04EN?

Are the AC units individually controllable?

According to the data you sent now it should work normally. I will try to debug this later today.

**Comment by veista** [comment]
> I‘m trying with cool mode. I don’t see the option unfortunately. When I turn it on using the app, this is what I see in HA: ![AD8CBA48-1F36-454F-8927-3D5628C52E60](https://user-images.githubusercontent.com/18214226/147845406-867a2564-70d6-4141-a186-0f4d5c2b490d.png)

You are also missing swing modes which is really weird behavior according to tha data.

**Comment by veista** [comment]
Also you do have disabledCapabilities listed, so the first bug makes no sense. Do you have other smartThings devices?

Can you send a picture of your ST IDE like this:
![image](https://user-images.githubusercontent.com/91916713/148269480-00d73e1f-aa8a-41d5-a729-18bb59b2f633.png)

Can you send a picture of you HA SmartThings Integration like this:
![image](https://user-images.githubusercontent.com/91916713/148279788-f51efa97-3f78-46d7-9e13-f6d0230e904d.png)

And also all devices like this:
![image](https://user-images.githubusercontent.com/91916713/148280003-77f7b936-aa48-4713-ae3d-879e4bdf7425.png)

**Comment by GaoMax** [comment]
The Data is from one of my AC Units (https://pastebin.com/A96BwWRW redid it, should be everything know).
ST IDE:
<img width="1284" alt="Bildschirmfoto 2022-01-06 um 10 35 13" src="https://user-images.githubusercontent.com/18214226/148319561-408b3a15-e42a-4f37-949b-305df1a0436a.png">
HA Integration:
<img width="333" alt="Bildschirmfoto 2022-01-06 um 10 38 36" src="https://user-images.githubusercontent.com/18214226/148319590-923cb5f8-9df5-458a-9cf2-07630a845995.png">
Devices:
<img width="983" alt="Bildschirmfoto 2022-01-06 um 10 38 40" src="https://user-images.githubusercontent.com/18214226/148319610-81f7a63f-1de1-480c-9440-6221c739b6e5.png">

All units are individually controllable. The MIM-H04EN is only there as the WiFi Gateway, itself can't be controlled.

**Comment by veista** [comment]
Thank you. I am at a loss here. Only thing that comes to mind is that you have not given your access token full push update permissions. Can you please make a new access token and make sure you allow every permission.

**Comment by veista** [comment]
Also could this be some UI bug. Can you print me all of your entity data from the climate entities like this also all entities from the MIM-H04EN:
![image](https://user-images.githubusercontent.com/91916713/148381639-b83ab28d-0e15-47ac-a67f-70bf140f8ed1.png)

**Comment by GaoMax** [comment]
I've given my Token every permission and reconfigured, but still no luck unfortunately.
Could be the support_features Tag! I've got 9 and you 57.
MIM-H04EN only has a single switch as an entity, and I've got no idea what it does.
<img width="1089" alt="Bildschirmfoto 2022-01-06 um 22 19 28" src="https://user-images.githubusercontent.com/18214226/148397079-853933b8-3448-45c2-837b-94a61353ba14.png">

**Comment by veista** [comment]
So it does work perfectly. I think it is your UI. Please make a new blank lovelace page and add the climate entity there.

**Comment by GaoMax** [comment]
Just tried it, also cleared my cache, accessed from integration, but still shows this, very weird behaviour.
<img width="606" alt="Bildschirmfoto 2022-01-06 um 22 29 19" src="https://user-images.githubusercontent.com/18214226/148398401-8cc8c48e-864d-4275-ba7f-f5208010a799.png">

**Comment by GaoMax** [comment]
https://pastebin.com/EzbxDWmK
I checked the html, I indeed don't have has-preset_mode or swing mode. Very weird, looking at the JS it seems like it should load if the entity has the attributes.

**Comment by GaoMax** [comment]
omg, it was my mistake ... I'm so sorry.
Before using your integration I created a custom one. I crafted it together with no prior knowledge of HA and SmartThings, so I had to hardcode some parameters and also had to use customize.yaml. I just remembered after seeing this, that customize.yaml might be overwriting these parameters, works great now. 
<img width="386" alt="Bildschirmfoto 2022-01-06 um 22 45 23" src="https://user-images.githubusercontent.com/18214226/148400767-23bc1b0c-c34a-4f52-ab09-c12dbff60d09.png">

**Comment by GaoMax** [comment]
Thank you for your amazing work,  this is truly a great project and a lot better than my previous implementation. Also thanks for the great support.

**Comment by veista** [comment]
No problem. It was good to revisit my code. Fixed alot of bugs. Btw. I will be patching out the light switch for your models, because your models do not support that ocf function.

**Comment by GaoMax** [comment]
Thank you so very much, this improves my HA experience a lot.
