### ISSUE TITLE
Error while setting up smartthings platform for sensor With HA 2022.4.0 

### ISSUE THREAD

**Issue by dankocrnkovic** [veista/smartthings#17]
With HA 2022.4.0 error started to apear:

Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:383
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 22:44:42 (2 occurrences)
Last logged: 22:44:42

Error adding entities for domain sensor with platform smartthings
Error while setting up smartthings platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by veista** [comment]
Hi,

Have you tried the latest (beta) version? I can not replicate this issue with 2022.4.0.

**Comment by dankocrnkovic** [comment]
I have not. I will wait for release then.

**Comment by veista** [comment]
Did the issue get resolved?

**Comment by dankocrnkovic** [comment]
Yes i has :)
Latest version fixed it.
Thank you!

danko

**Comment by veista** [comment]
You can close the issue if it got resolved and please remember to star the integration if you find it usefull. Thanks.
