### ISSUE TITLE
Volume and power is unavailable

### ISSUE THREAD

**Issue by dimmuboy** [veista/smartthings#2]
Volume sensor is `unavailable` and each power sensor is `unknown`

**Comment by veista** [comment]
Yes. Volume sensor has been replaced by number.volume. this gives you the ability to set 0 or 100% . Audio on or off. Power sensors have been removed from the climate entity and added as separate sensors.

**Comment by veista** [comment]
Please check from your climate entitys extra attributes that power sensors are not in disabled capabilities.

**Comment by veista** [comment]
I am looking into if disabled capabilities could be automatically excluded from being added. But for now you have to remove them by yourself.

**Comment by veista** [comment]
Please see the updates i made to v.1.0.2. I hope this fixes your problems.

**Comment by dimmuboy** [comment]
All mentioned sensors are unavailable now so it should be OK now because power is probably not available on my AC. In Smartthings app I can see only main unit power so maybe this is a problem.
btw it works via HACS, you're great man! 👍

**Comment by veista** [comment]
> All mentioned sensors are unavailable now so it should be OK now because power is probably not available on my AC. In Smartthings app I can see only main unit power so maybe this is a problem. btw it works via HACS, you're great man! 👍

Now you can delete the unavailable sensors. And in the future they will not be added if they are listed in Disabled capabilities.
