### ISSUE TITLE
Samsung AC missing filter usage period

### ISSUE THREAD

**Issue by liamlain** [veista/smartthings#30]
Hi, if would good to add Filter usage percentage in custom component.
AC Device info: ARTIK051_PRAC_20K
![tempFileForShare_20220710-151715](https://user-images.githubusercontent.com/93088569/178135186-6f98f456-0e52-4786-be7d-0ebb9fd90e11.jpg)

**Comment by veista** [comment]
The filter usage period is under filter reset.
