### ISSUE TITLE
Windfree (ARTIK051_PRAC_20K) temperature

### ISSUE THREAD

**Issue by thenightflier74** [veista/smartthings#33]
Hi, thanks for this howesome project. With my windfree split I can't use temperature as sensor. In fact, when a target value is reached, I'd like the split to change from "normal ventilation" to "windfree ventilation". In general, temperature can't be used as a trigger (while humidity yes). Many thanks for the support.

**Comment by luca-piccioni** [comment]
Same issue here. Temperature is not exposed as sensor, but it has many uses, even informational (i.e. graphs)

**Comment by luca-piccioni** [comment]
Just realized how to fix it: comparing with the original fork, [this line](https://github.com/veista/smartthings/blob/master/custom_components/smartthings/climate.py#L118) has been added. If I remove/delete this line, the temperature sensor is shown on HA, with its correct value.

Cannot understand the reason, but it works.

**Comment by thenightflier74** [comment]
Thanks for the test but the issue remains: the temperature appears as a sensor but it does not update

**Comment by dimmuboy** [comment]
I think I have same issue. Current temperature is still same.
In logs are only these two rows but I don't know if it's relevant
```
custom_components.smartthings.number::SmartThingsNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.smartthings.number::SamsungOcfTemperatureNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
```

**Comment by JRoc1212** [comment]
Model: 22K_REF_LCD_FHUB7.0

Not sure if this is similar but temperature shows as Unavailable for:
sensor.refrigerator_temperature_measurement
sensor.refrigerator_thermostat_cooling_setpoint

Added the model in the scripts and tried the above fix from luca-piccioni but no luck on getting temperature to report. I have the same two rows of logs that dimmuboy has as well. The temperature didn't report under the original fork either.

**Comment by dimmuboy** [comment]
In my case it;s not unavailable but static value in climate.device attribute _current_temperature_
Currently I have static value _current_temperature: 25_ but real temperature in room (and via SmartThings too) is 22°C

**Comment by thenightflier74** [comment]
I solved with a walkaround. By now it seems to work. 
1) I created a sensor in configuration.yaml

sensor splits:
  platform: template
  sensors:
    split_sala_temp:
      value_template: "{{ states.climate.split_sala.attributes['current_temperature'] | int }}"
      unit_of_measurement: '°C'
      friendly_name: 'Split Sala - Temperatura'

NOTE: you can add all the split in the same istance

2) I used a service call as action in the automation
service: climate.set_temperature
data:
  temperature: "{{ states('sensor.split_sala_temp') | float }}"
target:
  device_id: a52fc42e0a211ff72688a1511ec63d70

NOTE: this istance set the split temperature equals to the value catched by the split sensor itself. This because I use an external sensor to activate the action and then, when the target temperature is reached on the first sensor, I use the "current" temperature value of the split sensor as target temperature (that is higher due the air flow). Solution allow me to put the split on "maintain" mode rather then shut it off.

**Comment by veista** [comment]
Yes, template sensors is the way to go!
