### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by FilipRoels** [veista/smartthings#34]
Hi,

Great to see how people develop things just because they like it. I’m a rookie when it comes to Home Assistant.

I installed the original SmartThings but was a bit disappointed with the possibilities.
After some surfing on the net, I ended up on your Github. But I fail to install it. When I try to add your repository I get the message “https://github.com/veista/smartthings is not a valid add-on repository”. Manually installation, I don’t find the “custom_components” folder :-(.

can someone help me
thanks in advance
Filip

**Comment by veista** [comment]
Did you get your issues sorted?

**Comment by veista** [comment]
#48
