### ISSUE TITLE
Error: config flow cant be loaded: undefined

### ISSUE THREAD

**Issue by mitchoklemen** [veista/smartthings#37]
Hi,
I have problem setup smartthings custom. I do install it in HACS, restart HA, but when try to add integration I cant set it up.
I get:  
Error: config flow cant be loaded: undefined

I did try to uninstall it in HACS, restart and setup the original smartthings but I get same error

Where to start solving?

Thank you, Mitcho

**Comment by veista** [comment]
Did this get fixed with the latest release?

**Comment by mitchoklemen** [comment]
It was Fixed when I edit config with...

homeassistant:
  external_url: "https://xxxxx"
  internal_url:  "https://xxxxx"
