### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by Milanmilunovic** [veista/smartthings#38]
Hello, I am having a problem with integration. Each month it gives me message "failed to set up" and when I set it up again, it works for one month. Is there something I don't know, or any known solution for this problem? 
Thanks

**Comment by veista** [comment]
Did this get fixed with the latest release?

**Comment by Milanmilunovic** [comment]
I am not sure, but it is true that it didn't disconect for a while... I will let you know if it happens again.
