### ISSUE TITLE
[Feature Request] Turn display on/off on details screen

### ISSUE THREAD

**Issue by metropt** [veista/smartthings#4]
Hi,
Do you think it is possible to turn on/off the light on the details screen:

![image](https://user-images.githubusercontent.com/764040/142079473-e59cb3df-e720-437f-8a5f-60cca18275e8.png)

Thank you

**Comment by veista** [comment]
Yes. You can create your own climate card to do this. You can then share it on HACS.

**Comment by veista** [comment]
I maybe misunderstood the question. I can look into this, but i dont think it is something worth while so no promises.

**Comment by metropt** [comment]
I think you understand correctly my request. I'll try to look into the climate card and edit it to be able to turn on/off the light on the details page of the card.

**Comment by veista** [comment]
![image](https://user-images.githubusercontent.com/91916713/142298914-9d3e3122-6e38-4ca3-b253-ecb54357a2fb.png)
If you mean adding it as a entity category, I can try to do that.
