### ISSUE TITLE
Cannot set custom repository 

### ISSUE THREAD

**Issue by spanzetta** [veista/smartthings#48]
Hello

I have these versions:
Home Assistant 2022.12.3
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221208.0 - latest

And when I put the link https://github.com/veista/smartthings  HA says "https://github.com/veista/smartthings is not a valid add-on repository"
So cannot start to setup it

Am I doing something wrong?

Thanks

**Comment by veista** [comment]
Yes. This not a add-on repository, but a custom integration. https://hacs.xyz/

**Comment by spanzetta** [comment]
Oook.. thanks for clarification..
;-)
