### ISSUE TITLE
Conflict with builtin SmartThings integration..

### ISSUE THREAD

**Issue by spanzetta** [veista/smartthings#49]
Again here with another issue (I was then able to install it .. ;-)

When I try to add the integration I get the error shown here

![image](https://user-images.githubusercontent.com/49818743/207369251-3cd9e18e-1696-4573-b54d-5bdf56a57ecc.png)

Pls note that it's a new HA installation and I didn't configure the standard/builtin Smartthings integration.. so there is nothing to delete.
I already cleaned the browser cache (tried different browser too)
I also tried to delete config/.storage/smartthing but at next restart it appears again the webhook error..

What am I doing wrong?

Thanks in advance

**Comment by veista** [comment]
You should follow the instructions from the official integration. https://www.home-assistant.io/integrations/smartthings/

**Comment by spanzetta** [comment]
I did already (before writing here) .. but didn't find anything wrong..
Any hints? 
Thanks

**Comment by spanzetta** [comment]
I mean... what's written there is to integrate the "original" SmartThings (which requires SSL remote access or HA Cloud from Nabuca).. but that's not what I want to use.. I want to use your custom integration which is much better from what I read  ..
Thanks

**Comment by veista** [comment]
The setup is exactly the same.

**Comment by spanzetta** [comment]
ah ok... so I must solve the SSL issues for remote access (I am currenly stopped at this point)

**Comment by veista** [comment]
Yes.

**Comment by veista** [comment]
The data is updated with callbacks. Meaning it updates only when data has changed.

**Comment by veista** [comment]
I don't think devices update when they are off.

**Comment by veista** [comment]
I don't know. You will have to find out yourself.

**Comment by Ciccia89** [comment]
> I was able to finish setup ;-)
> 
> It works great!!!
> 
> but only one issue .. I see that data are updated rarely.. is there a setting to make more frequent update?
> 
> See screenshot attached (data was updated 14 hours ago)..
> 
> Thanks
> 
> ![image](https://user-images.githubusercontent.com/49818743/207531939-a0a2f058-5abc-4cfa-ad04-4bbf81a7b6c5.png)
> 
> ![Screenshot_20221214_081736_Home Assistant.jpg](https://user-images.githubusercontent.com/49818743/207531007-f698694b-71ee-42e8-b120-61321d81f1dc.jpg)

Hello, I don't wanna bother anyone but I want to speak in Italian with Spanzetta, so it will be faster and better to understand :)

Ciao, scusa se ti disturbo ma come hai risolto? Io ho lo stesso problema. 
Io avendo una connessione con il 4g accedo dall'esterno tramite un Cloudflare e credo possa essere questo il problema giusto? 

Grazie in anticipo

**Comment by spanzetta** [comment]
Ciao 
In realtà non ho risolto.. nel senso che gli aggiornamenti sono piuttosto rari e non in tempo reale.. 
Lo tengo così..

**Comment by Ciccia89** [comment]
> Ciao In realtà non ho risolto.. nel senso che gli aggiornamenti sono piuttosto rari e non in tempo reale.. Lo tengo così..

Grazie per la risposta: 
Io sono ancora più indietro, non sono riuscito ad integrarlo perchè mi da l'errore che avevi tu all'inizio :)

Come hai fatto a risolverlo?

grazie ancora

**Comment by spanzetta** [comment]
se ricordo bene ha iniziato a funzionare dopo aver configurato SSL/HTTPS (che è richiesto come mandatory) .. per cui prima configura duckdns (io ho usato quello) e poi dovrebbe andare senza problemi seguendo la guida ..

**Comment by Ciccia89** [comment]
Ok io purtroppo avendo una connessione NAT 4G, non riesco ad usare DuckDNS ma uso Cloudflare e tramite quello comunque non mi fa entrare... tu immagino abbia una connessione non NAT.
