### ISSUE TITLE
Push message limit?

### ISSUE THREAD

**Issue by spanzetta** [veista/smartthings#52]
What is this error? How to solve it?

This error originated from a custom integration.

Logger: custom_components.smartthings.smartapp
Source: custom_components/smartthings/smartapp.py:376
Integration: SmartThings
First occurred: December 20, 2022 at 7:54:00 PM (1 occurrences)
Last logged: December 20, 2022 at 7:54:00 PM

Some device attributes may not receive push updates and there may be subscription creation failures under app 'a533278b-2eb6-409d-83c1-f6bad6c04fd0' **because 75 subscriptions are required but there is a limit of 40 per app**

**Comment by veista** [comment]
#14
