### ISSUE TITLE
Integration error since HA core version 5.0 for Samsung oven (TP1X_DA-KS-OVEN-01061)

### ISSUE THREAD

**Issue by brunotfr** [veista/smartthings#73]
Every core update after core_2023.4.6 breaks the integration with this error:

Logger: homeassistant.config_entries Source: custom_components/smartthings/__init__.py:186 Integration: SmartThings First occurred: 10:04:35 (1 occurrences) Last logged: 10:04:35
Error setting up entry Mijn huis for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthings/__init__.py", line 186, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Tried removing and adding the integration.
Also tried a new token, but the same error.

As soon as I revert to core core_2023.4.6 it works immediately.

**Comment by veista** [comment]
Please update the integration.

**Comment by brunotfr** [comment]
Just realized that and working on it.

**Comment by brunotfr** [comment]
That did the trick.

**Comment by brunotfr** [comment]
Overlooked to manualy update the integration.
After updating it works like a charme.
