### ISSUE TITLE
Temperature Updates Not Occurring Without Module Reload

### ISSUE THREAD

**Issue by omerfaruk-aran** [veista/smartthings#88]
Hello,

I hope this message finds you well. I wanted to bring to your attention an issue I've encountered in the project related to temperature updates within the climate control module.

Currently, it seems that the temperature updates for the air conditioning system do not occur automatically unless the module is reloaded. This behavior raises a couple of questions:

Update Frequency: Could you please provide some information about the expected frequency of temperature updates? Understanding how often the temperature readings are supposed to be refreshed will help me better understand the problem.

Modification of Update Frequency: Is there a way to modify the frequency of these updates? It would be helpful if there is a configurable parameter or setting that can be adjusted to control how often the temperature updates take place. This could be beneficial for scenarios where real-time or frequent updates are required.

I'm eager to assist in resolving this issue, and I appreciate your time and effort in maintaining this project. If there are any specific details, logs, or code snippets you need from me to investigate further, please let me know, and I'd be happy to provide them.

Thank you for your attention to this matter.

Best regards,

Ömer Faruk ARAN
omerfaruk@aran.net.tr

**Comment by veista** [comment]
Hi,

This is one common issue and the n:th duplicate.

Update frequency: this it is a callback system. The only poll cycle is at load.

Modify update frequency: not feasible with this integration.

Resolving this issue: #86

Thanks
