### ISSUE TITLE
TypeError: 'types.GenericAlias' object is not iterable

### ISSUE THREAD

**Issue by GaoMax** [veista/smartthings#9]
Hey,
great work! I'm getting a error on setup:
`  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/smartthings/__init__.py", line 148, in async_setup_entry
    await smartapp_sync_subscriptions(
  File "/config/custom_components/smartthings/smartapp.py", line 362, in smartapp_sync_subscriptions
    for disabled_capability in disabled_capabilities:
TypeError: 'types.GenericAlias' object is not iterable`

I'm using the current 1.0.5 version. Any ideas?
Happy Holidays!

**Comment by veista** [comment]
Hi. Could you please see issue number 6 and take a picture of your custom.disabledCapabilities. Thanks.

**Comment by GaoMax** [comment]
Hi! I've taken a look at issue 6 and I have placeholder as the type too. But it can't change it, because it requires me to enter a Device Network Id, which is currently empty and I don't know what value I should choose.

**Comment by GaoMax** [comment]
Using a random string seems to work fine.
[
    "",
    "custom.airConditionerTropicalNightMode",
    "audioVolume",
    "remoteControlStatus",
    "custom.airConditionerOdorController",
    "airQualitySensor",
    "dustSensor",
    "veryFineDustSensor",
    "odorSensor",
    "demandResponseLoadControl",
    "relativeHumidityMeasurement",
    "custom.deodorFilter",
    "custom.eletricHepaFilter",
    "custom.hepaFilter",
    "custom.veryFineDustFilter",
    "custom.periodicSensing",
    "custom.doNotDisturbMode"
]

Is there for my acs. but my controller device doesn't seem to have disabled capabilities. Maybe it's trying to iterate through a empty list?

**Comment by veista** [comment]
Hi. Thanks for your reply. Indeed the first item is null. On my ACs I have two identical lines which causes problems. This seems to be a buggy fearure on these ACs. I will try to fix this in a couple of days and I will release it as beta on HACS until you resolve this issue. Happy Holidays to you too btw.

**Comment by veista** [comment]
Hi,

I found the bug. It was an indentation error in my code. Sorry for the inconvenience. I made a pre-release of the integration, which should fix the issue.

**Comment by condor872** [comment]
Same issue here. There is a solution?

**Comment by veista** [comment]
> Same issue here. There is a solution?
You can try pre-release 1.0.6. You have to enamble beta releases in the Integration in HACS

**Comment by condor872** [comment]
> > Same issue here. There is a solution?
> 
> You can try pre-release 1.0.6. You have to enable beta releases in the Integration in HACS

Problem solved. Very thanks for your work

**Comment by veista** [comment]
> > > Same issue here. There is a solution?
> > 
> > 
> > You can try pre-release 1.0.6. You have to enable beta releases in the Integration in HACS
> 
> Problem solved. Very thanks for your work

That is great news. Please don't forget to star the repo if you like the integration. Thanks!

**Comment by veista** [comment]
I now made 1.0.6 as the latest release. Please close this issue if it is resolved.

**Comment by GaoMax** [comment]
Works great! Thanks for the patch.

**Comment by veista** [comment]
> Works great! Thanks for the patch.

Thats great! Please star the repo if you like the integration.
