### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by CodeFatherG** [veista/smartthings#93]
I'd like to fix air purifier devices but the core integration is no longer maintained. Is this maintained and can I leverage this project to fix it?

**Comment by veista** [comment]
I am not adding new features to this repository. You can of course leverage this project to fix your issues.

**Comment by FilipeOS** [comment]
Is this why don't show in HACS store?

**Comment by veista** [comment]
This integration is not HACS "store" compatible, since it is a fork of an existing integration.

**Comment by FilipeOS** [comment]
So this is not updated?

HACS
Remove your original smartthings integration if you have one set up (optional)
Add https://github.com/veista/smartthings as a Custom Repository
Install SmartThings Custom from the HACS Integrations tab
Restart Home Assistant
Install SmartThings from the HA Integrations tab
Enjoy!

**Comment by veista** [comment]
[No ](https://hacs.xyz/docs/publish/include)
