### ISSUE TITLE
Fridge freezer entities no longer reported by ST 

### ISSUE THREAD

**Issue by blair287** [veista/smartthings#97]
Hi,

My fridge freeze isn't showing most of its entities anymore set points temps etc are unavalible but doors and energy are working no issues with my dishwasher or washing machine dunno if samsung changed something.

![Screenshot_20240105_122526_Home Assistant](https://github.com/veista/smartthings/assets/44187409/6f0641e7-23d8-4d44-b16e-33663f3a07ef)

**Comment by Sdahl1234** [comment]
My fridge got an update and change from 22K_REF_LCD_FHUB7.0 to 23K_REF_LCD_FHUB8.0.

**Comment by blair287** [comment]
> My fridge got an update and change from 22K_REF_LCD_FHUB7.0 to 23K_REF_LCD_FHUB8.0.

Ah ill check that then

**Comment by blair287** [comment]
> My fridge got an update and change from 22K_REF_LCD_FHUB7.0 to 23K_REF_LCD_FHUB8.0.

That fixed it thanks!

**Comment by blair287** [comment]
Check model number hasn't changed if your having same issue solution above!

**Comment by blair287** [comment]
> My fridge got an update and change from 22K_REF_LCD_FHUB7.0 to 23K_REF_LCD_FHUB8.0.

is yours still working? mines exhibiting the same behaviour but the model number appears to still be the same.
